import fs from "fs/promises";
import path from "path";
import { CONFIG_PATHS } from "@/utils/constants";

/**
 * The runner script installed at ~/.claude/hooky-notify.sh.
 *
 * This content is STATIC -- it never changes when you edit a sound or a
 * footer. All behavior is read from ~/.claude/hooky.json and
 * ~/.claude/hooky-projects.json at fire time, which means:
 *   - the app never regenerates or re-parses shell code
 *   - editing either JSON by hand takes effect immediately
 *   - a broken/missing config degrades to silence, never to a hook error
 *
 * The script drives two independent output channels:
 *
 *   banner  terminal-notifier, backgrounded and fire-and-forget, any event.
 *   footer  a {systemMessage, suppressOutput} object on stdout, which Claude
 *           Code parses and prints in the terminal. Stop only, and necessarily
 *           synchronous -- it is the process's exit value, not a side effect.
 *
 * Hooks run on Claude Code's critical path, so every failure mode exits 0 and
 * the cost is bounded: two jq calls for the sound/banner path, plus two more
 * only on a Stop that actually has a footer to draw. Nothing here shells out
 * to git -- footer tokens resolve from the payload and from string work alone,
 * so drawing a footer spawns no processes. The only exceptions are opt-in link
 * conditions (`port:` probes, `env:` lookups), which run solely for links that
 * declare one.
 *
 * TARGET: bash 3.2, the version macOS ships. No associative arrays, no
 * mapfile, and every array expansion is guarded by a counter because
 * ${arr[@]} on an empty array is an error under `set -u`.
 */
export const RUNNER_MARKER = "# hooky:managed";

export const RUNNER_SCRIPT = `#!/usr/bin/env bash
${RUNNER_MARKER} -- generated by Hooky. Safe to delete; do not hand-edit.
#
# Reads ~/.claude/hooky.json and ~/.claude/hooky-projects.json at runtime. To
# change a sound or a footer, edit those files (or use the Hooky UI) -- this
# script does not need to be regenerated.

set -uo pipefail

CONFIG="\${HOOKY_CONFIG:-$HOME/.claude/hooky.json}"
PROJECTS="\${HOOKY_PROJECTS:-$HOME/.claude/hooky-projects.json}"

# Any missing prerequisite means "do nothing", never "fail the hook".
command -v jq >/dev/null 2>&1 || exit 0

INPUT=$(cat 2>/dev/null || true)
[[ -z "\${INPUT:-}" ]] && INPUT="{}"

# Fields are joined with US (0x1f) rather than tabs: tab is an IFS *whitespace*
# character, so bash's read would collapse runs of them and silently shift every
# value left past an empty field. US is not whitespace, so empty fields survive.
SEP=$'\\037'

# --- one jq pass over the hook payload ---------------------------------
# Field list mirrors EVENT_META.fields in src/types/soundEvents.ts. .cwd is
# appended here rather than read separately so the footer's project lookup
# costs no extra pass over the payload.
PAYLOAD=$(printf '%s' "$INPUT" | jq -r '
  [ .hook_event_name, .tool_name, .model, (.tool_input.file_path?),
    .agent_type, .reason, .error, .trigger, .source,
    .teammate_name, .team_name, .task_subject,
    .name, .worktree_path, .mcp_server_name, .message, .notification_type,
    .cwd ]
  | map(if . == null then "" else (tostring | gsub("[\\n\\r\\u001f]"; " ")) end)
  | join("\\u001f")' 2>/dev/null) || exit 0

IFS="$SEP" read -r HOOK TOOL MODEL FILE AGENT REASON ERRTEXT TRIGGER SOURCE \\
  TEAMMATE TEAM TASK WNAME WPATH SERVER EMESSAGE NOTIFYTYPE CWD <<< "$PAYLOAD"

[[ -n "\${HOOK:-}" ]] || exit 0

# --- live monitor trace -------------------------------------------------
# Deliberately a bare append, not a curl: this runs on Claude Code's critical
# path, so the trace must cost no subprocess and must not depend on anything
# listening. \`>>\` is O_APPEND, so two sessions firing at once cannot interleave
# a short line. No timestamp is written -- bash 3.2 has no EPOCHREALTIME, and a
# \`date\` fork would cost more than the whole rest of this block; the reader
# stamps arrival time instead. Logged BEFORE the enabled/muted check so the
# monitor shows events whose sound is off.
EVENTS="\${HOOKY_EVENTS:-$HOME/.claude/hooky-events.log}"
printf '%s\\037%s\\037%s\\037%s\\n' \\
  "\${HOOK:-}" "\${TOOL:-}" "\${MODEL:-}" "\${CWD:-}" >> "$EVENTS" 2>/dev/null || true

# --- one jq pass over the sound config ----------------------------------
# Empty output means "stay silent": global mute, unknown event, or the event
# is disabled. Booleans are compared explicitly because jq's \`//\` operator
# falls through on \`false\` as well as \`null\`, so \`.enabled // true\` would
# yield true for an explicitly disabled event.
SETTINGS=""
if [[ -f "$CONFIG" ]]; then
  SETTINGS=$(jq -r --arg h "$HOOK" '
    if (.enabled == false) then ""
    else (.events[$h] // null) as $e
    | if ($e == null) or ($e.enabled == false) then ""
      else [ ($e.soundPath // ""),
             (($e.volume // 1) | tostring),
             (($e.banner != false) | tostring),
             ($e.emoji // ""),
             ($e.message // ""),
             (($e.includeDetails == true) | tostring) ]
           | map(gsub("[\\n\\r\\u001f]"; " ")) | join("\\u001f")
      end
    end' "$CONFIG" 2>/dev/null) || SETTINGS=""
fi

# A muted event still falls through to the footer below: a project footer is
# configured independently of whether Stop plays a sound, so exiting here --
# as an earlier version did -- would make "silent Stop" also mean "no footer".
if [[ -n "$SETTINGS" ]]; then
  IFS="$SEP" read -r SOUND_PATH VOLUME BANNER EMOJI MESSAGE DETAILS <<< "$SETTINGS"

  # --- sound -----------------------------------------------------------
  # afplay rather than terminal-notifier's -sound so that any audio file works,
  # not just the names macOS recognizes, and so volume is controllable.
  if [[ -n "\${SOUND_PATH:-}" && -f "$SOUND_PATH" ]]; then
    ( afplay -v "\${VOLUME:-1}" "$SOUND_PATH" >/dev/null 2>&1 & ) >/dev/null 2>&1
  fi

  # --- banner ----------------------------------------------------------
  if [[ "\${BANNER:-true}" == "true" ]] && command -v terminal-notifier >/dev/null 2>&1; then
    FILE_BASE=""
    [[ -n "\${FILE:-}" ]] && FILE_BASE=\${FILE##*/}

    # Pure parameter expansion -- no subprocess per placeholder.
    MESSAGE="\${MESSAGE//\\{hook\\}/$HOOK}"
    MESSAGE="\${MESSAGE//\\{tool\\}/$TOOL}"
    MESSAGE="\${MESSAGE//\\{model\\}/$MODEL}"
    MESSAGE="\${MESSAGE//\\{file\\}/$FILE_BASE}"
    MESSAGE="\${MESSAGE//\\{agent\\}/$AGENT}"
    MESSAGE="\${MESSAGE//\\{reason\\}/$REASON}"
    MESSAGE="\${MESSAGE//\\{error\\}/$ERRTEXT}"
    MESSAGE="\${MESSAGE//\\{trigger\\}/$TRIGGER}"
    MESSAGE="\${MESSAGE//\\{source\\}/$SOURCE}"
    MESSAGE="\${MESSAGE//\\{teammate\\}/$TEAMMATE}"
    MESSAGE="\${MESSAGE//\\{team\\}/$TEAM}"
    MESSAGE="\${MESSAGE//\\{task\\}/$TASK}"
    MESSAGE="\${MESSAGE//\\{name\\}/$WNAME}"
    MESSAGE="\${MESSAGE//\\{path\\}/$WPATH}"
    MESSAGE="\${MESSAGE//\\{server\\}/$SERVER}"
    MESSAGE="\${MESSAGE//\\{message\\}/$EMESSAGE}"
    MESSAGE="\${MESSAGE//\\{notifyType\\}/$NOTIFYTYPE}"

    [[ -n "\${EMOJI:-}" ]] && MESSAGE="$EMOJI $MESSAGE"

    if [[ "\${DETAILS:-false}" == "true" ]]; then
      [[ -n "$TOOL" ]] && MESSAGE="$MESSAGE
Tool: $TOOL"
      [[ -n "$MODEL" ]] && MESSAGE="$MESSAGE
Model: $MODEL"
      [[ -n "$FILE_BASE" ]] && MESSAGE="$MESSAGE
File: $FILE_BASE"
    fi

    ( terminal-notifier \\
        -title "Claude Code" \\
        -message "$MESSAGE" \\
        -group "claude-code" >/dev/null 2>&1 & ) >/dev/null 2>&1
  fi
fi

# --- footer (Stop only) -------------------------------------------------
# Everything past this point writes to stdout, so it must run only where
# Claude Code expects a hook result object.
[[ "$HOOK" == "Stop" ]] || exit 0
[[ -f "$PROJECTS" ]] || exit 0

[[ -n "\${CWD:-}" && -d "$CWD" ]] || CWD="$PWD"

# Longest matching registered path wins, so nested projects resolve to the
# innermost one. Keys are expanded against $HOME first, because a hand-edited
# config may well store them with a tilde.
#
# The entry is bound to $p before the prefix test on purpose. jq evaluates a
# filter's arguments against that filter's *input*, so the obvious spelling --
# \`$cwd | startswith(.key + "/")\` -- resolves .key against the $cwd string
# rather than the entry, which aborts the whole query and silently kills every
# footer. Binding first makes the reference unambiguous.
BLOB=$(jq -r --arg cwd "$CWD" --arg home "$HOME" '
  def clean: tostring | gsub("[\\n\\r\\u001f]"; " ");
  if (.enabled == false) then empty
  else
    ( (.projects // {}) | to_entries
      | map(.key |= (if startswith("~") then ($home + .[1:]) else . end))
      | map(select(. as $p | ($p.key == $cwd) or ($cwd | startswith($p.key + "/"))))
      | sort_by(.key | length) | last ) as $hit
    | ( if $hit == null
        then (if (.default // null) == null then null else {key: $cwd, value: .default} end)
        else $hit end ) as $e
    | if ($e == null) or ($e.value.enabled == false) then empty
      else $e.value as $p
      | (["H", ($p.icon // "" | clean), ($p.title // "" | clean), ($e.key | clean)] | join("\\u001f")),
        (($p.meta // [])[]  | ["M", clean] | join("\\u001f")),
        (($p.links // [])[] | ["L", (.label // "" | clean), (.url // "" | clean), (.when // "" | clean)] | join("\\u001f")),
        (($p.notes // [])[] | ["N", clean] | join("\\u001f"))
      end
  end' "$PROJECTS" 2>/dev/null) || exit 0

[[ -n "$BLOB" ]] || exit 0

ICON=""; TITLE=""; ROOT=""
META_N=0; LINK_N=0; NOTE_N=0
META=(); LINKS=(); NOTES=()

while IFS= read -r RECORD; do
  [[ -z "$RECORD" ]] && continue
  IFS="$SEP" read -r RKIND RF1 RF2 RF3 <<< "$RECORD"
  case "$RKIND" in
    H) ICON="$RF1"; TITLE="$RF2"; ROOT="$RF3" ;;
    M) META[$META_N]="$RF1"; META_N=$((META_N + 1)) ;;
    L) LINKS[$LINK_N]="$RF1$SEP$RF2$SEP$RF3"; LINK_N=$((LINK_N + 1)) ;;
    N) NOTES[$NOTE_N]="$RF1"; NOTE_N=$((NOTE_N + 1)) ;;
  esac
done <<< "$BLOB"

[[ -n "$ROOT" ]] || exit 0
[[ -n "$TITLE" ]] || TITLE=\${ROOT##*/}

DIRNAME=\${CWD##*/}
REL=\${CWD#$ROOT}
REL=\${REL#/}

# date is the only optional subprocess on the footer path, and only when a
# token actually asks for it.
NOW_DATE=""; NOW_TIME=""
case "$BLOB" in *"{date}"*) NOW_DATE=$(date +%Y-%m-%d 2>/dev/null) ;; esac
case "$BLOB" in *"{time}"*) NOW_TIME=$(date +%H:%M 2>/dev/null) ;; esac

resolve() {
  local s="$1"
  s="\${s//\\{project\\}/$TITLE}"
  s="\${s//\\{dir\\}/$DIRNAME}"
  s="\${s//\\{cwd\\}/$CWD}"
  s="\${s//\\{root\\}/$ROOT}"
  s="\${s//\\{rel\\}/$REL}"
  s="\${s//\\{model\\}/$MODEL}"
  s="\${s//\\{date\\}/$NOW_DATE}"
  s="\${s//\\{time\\}/$NOW_TIME}"
  printf '%s' "$s"
}

# Link conditions. An unrecognized condition fails OPEN -- a typo should show
# the link, not silently swallow it.
cond_ok() {
  local w="$1" neg=0 rc=1 p
  [[ -z "$w" ]] && return 0
  if [[ "\${w:0:1}" == "!" ]]; then neg=1; w=\${w:1}; fi

  case "$w" in
    port:*)
      p=\${w#port:}
      if [[ $p =~ ^[0-9]+$ ]] && command -v nc >/dev/null 2>&1; then
        nc -z -w 1 127.0.0.1 "$p" >/dev/null 2>&1 && rc=0
      fi
      ;;
    file:*)
      [[ -e "$ROOT/\${w#file:}" ]] && rc=0
      ;;
    env:*)
      [[ -n "$(printenv "\${w#env:}" 2>/dev/null)" ]] && rc=0
      ;;
    *)
      rc=0
      ;;
  esac

  if [[ $neg -eq 1 ]]; then
    [[ $rc -eq 0 ]] && return 1
    return 0
  fi
  return $rc
}

RULE="───────────────────────────────────────────────"
HEADER=$(resolve "$TITLE")
[[ -n "$ICON" ]] && HEADER="$ICON  $HEADER"

BODY="$RULE"$'\\n'"$HEADER"$'\\n'

if [[ $META_N -gt 0 ]]; then
  CHUNK=""
  I=0
  while [[ $I -lt $META_N ]]; do
    LINE=$(resolve "\${META[$I]}")
    [[ -n "$LINE" ]] && CHUNK="$CHUNK  $LINE"$'\\n'
    I=$((I + 1))
  done
  [[ -n "$CHUNK" ]] && BODY="$BODY"$'\\n'"$CHUNK"
fi

if [[ $LINK_N -gt 0 ]]; then
  CHUNK=""
  I=0
  while [[ $I -lt $LINK_N ]]; do
    IFS="$SEP" read -r LLABEL LURL LWHEN <<< "\${LINKS[$I]}"
    I=$((I + 1))
    [[ -z "$LURL" ]] && continue
    cond_ok "$LWHEN" || continue
    LLABEL=$(resolve "$LLABEL")
    LURL=$(resolve "$LURL")
    printf -v ROW '  %-22s %s' "$LLABEL" "$LURL"
    CHUNK="$CHUNK$ROW"$'\\n'
  done
  [[ -n "$CHUNK" ]] && BODY="$BODY"$'\\n'"$CHUNK"
fi

if [[ $NOTE_N -gt 0 ]]; then
  CHUNK=""
  I=0
  while [[ $I -lt $NOTE_N ]]; do
    LINE=$(resolve "\${NOTES[$I]}")
    [[ -n "$LINE" ]] && CHUNK="$CHUNK  $LINE"$'\\n'
    I=$((I + 1))
  done
  [[ -n "$CHUNK" ]] && BODY="$BODY"$'\\n'"$CHUNK"
fi

BODY="$BODY$RULE"

# suppressOutput keeps the raw stdout out of the transcript; systemMessage is
# what actually gets shown to the user.
jq -n --arg msg "$BODY" '{systemMessage: $msg, suppressOutput: true}'

exit 0
`;

export class RunnerService {
  /** Write (or refresh) the runner script and make it executable. */
  async install(): Promise<string> {
    await fs.mkdir(path.dirname(CONFIG_PATHS.runner), { recursive: true });
    await fs.writeFile(CONFIG_PATHS.runner, RUNNER_SCRIPT, "utf-8");
    await fs.chmod(CONFIG_PATHS.runner, 0o755);
    return CONFIG_PATHS.runner;
  }

  async isInstalled(): Promise<boolean> {
    try {
      const content = await fs.readFile(CONFIG_PATHS.runner, "utf-8");
      return content.includes(RUNNER_MARKER);
    } catch {
      return false;
    }
  }

  /** True when the on-disk script is stale relative to this build. */
  async needsRefresh(): Promise<boolean> {
    try {
      const content = await fs.readFile(CONFIG_PATHS.runner, "utf-8");
      return content !== RUNNER_SCRIPT;
    } catch {
      return true;
    }
  }

  async remove(): Promise<void> {
    await fs.rm(CONFIG_PATHS.runner, { force: true });
  }

  get scriptPath(): string {
    return CONFIG_PATHS.runner;
  }
}

export const runnerService = new RunnerService();
